### ISSUE TITLE
'New Person' vs. 1.9.1 not working

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#305] opened 2016-12-23 19:52 UTC
From top menu: People - New Person ...returns error message:
"We're sorry, but something went wrong.
If you are the application owner check the logs for more information."
version 1.9.1

**Comment by VanAuken** [comment] 2016-12-23 19:56
From top menu:  Reports - Attendance Sheet .... also returns the same error message.  The two may be related.

**Comment by kgf** [comment] 2016-12-23 23:59
I could not reproduce the New person issue on the HEAD of development branch. I _could_ reproduce the attendance sheet issue. @VanAuken could you please create a new issue for the attendance sheet ? 
I'll leave this open with a tag until the next deploy, then we'll verify it's fixed in production.

**Comment by Spandana-Sai** [comment] 2016-12-26 09:37
@kgf Added code @department = Department.where(shortname: "BAUX").first is causing error as there is no BAUX  by default in database. Can you please let me know reason behind hard-coding so that I can fix the issue.

**Comment by kgf** [comment] 2016-12-27 15:04
@Spandana-Sai Thanks for taking a look at this. I'm not sure if this is the cause of the issue, but I certainly do not like the hard coded references, but needed to get things working. I would appreciate it if you could take a look at removing them for the two reports, org chart and attendance sheet. I would like them to be dynamic based on the departments. If you take a look at @pcai work here, I think it will help.
Thanks !
Kevin
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/layouts/_top_menu.html.erb#L18

**Comment by kgf** [comment] 2017-01-09 00:11
Here is almost the actual error message from the logs
```
I, [2017-01-09T00:09:56.982505 #31666]  INFO -- : Started GET "/people/new" for 111.111.111.111 at 2017-01-09 00:09:56 +0000
I, [2017-01-09T00:09:56.983563 #31666]  INFO -- : Processing by PeopleController#new as HTML
I, [2017-01-09T00:09:57.007995 #31666]  INFO -- :   Rendered people/_form.html.erb (15.7ms)
I, [2017-01-09T00:09:57.008142 #31666]  INFO -- :   Rendered people/new.html.erb within layouts/application (16.0ms)
I, [2017-01-09T00:09:57.008344 #31666]  INFO -- : Completed 500 Internal Server Error in 25ms (ActiveRecord: 0.5ms)
F, [2017-01-09T00:09:57.009496 #31666] FATAL -- : 
ActionView::Template::Error (undefined method `model_name' for nil:NilClass):
    22:                               value: format_date_value(f.object.application_date) } %>
    23: 
    24:       <h2> Phone information </h2>
    25:       <%= f.simple_fields_for @phone, wrapper: :horizontal_input_group do |c| %>
    26:         <fieldset>
    27:           <%= c.input :id, :as => :hidden %>
    28:           <%= c.input :category, :as => :select, :collection => Channel::CATEGORIES %>
  app/views/people/_form.html.erb:25:in `block in _app_views_people__form_html_erb__805422181679907032_46950544820040'
  app/views/people/_form.html.erb:1:in `_app_views_people__form_html_erb__805422181679907032_46950544820040'
  app/views/people/new.html.erb:6:in `_app_views_people_new_html_erb___2542167342664793662_46950544875300'
  app/controllers/people_controller.rb:97:in `new'
```

**Comment by kgf** [comment] 2017-02-14 03:00
There was a data issue around old phone records

**Closed as completed by kgf** 2017-02-14 03:00 UTC
Labels: bug, On Hold
