### ISSUE TITLE
New Person form: zipcode entry should fill in city and state

### ISSUE THREAD

**Issue by VanAuken** [ReadyResponder/ReadyResponder#169] opened 2016-10-05 12:23 UTC
In order to aid data entry, in the new person form, entering the zipcode should fill in the appropriate city and state.

**Comment by kgf** [comment] 2016-10-05 12:57
Thanks, but this is a duplicate of #98, which is still open. I will bump that issue.

**Closed as completed by kgf** 2016-10-05 12:57 UTC
